name: Compile LaTeX Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache TeX Live
        uses: actions/cache@v3
        with:
          path: /usr/local/texlive
          key: texlive-2023-${{ runner.os }}
          restore-keys: texlive-2023-
      
      - name: Install Minimal LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-xetex \
            texlive-fonts-extra


      - name: Create output directory
        run: mkdir -p output && chmod 777 output  # Ensure output directory exists and is writable

      - name: Compile LaTeX to PDF
        run: pdflatex -interaction=nonstopmode -output-directory=output resume.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: output/resume.pdf

      - name: Commit & Push Compiled PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv output/resume.pdf .
          git add -f resume.pdf
          git commit -m "Update compiled resume PDF" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Release Resume PDF
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf
          tag_name: latest
          name: "Latest Resume Release"
          body: "This is the latest compiled resume PDF."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

